# Generated by Django 4.0.3 on 2022-04-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_name_message_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
